name: Basic Workflow
on:
    push:
        branches: [develop]
        tags: ["*"]

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: List downloaded
              run: ls -l
            - name: Install poetry
              run: pipx install poetry
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'poetry'
                cache-dependency-path: "poetry.lock"
            - name: Installing Dependencies
              run: poetry install
    test:
        needs: [install-dependencies]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install poetry
              run: pipx install poetry
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'poetry'
            - name: Installing Dependencies
              run: poetry install --with test
            - name: Running Tests
              run: poetry run pytest
  
    build-and-push-image:
      needs: [test]
      runs-on: ubuntu-latest
      steps:
        - name: Build and Deploy
          uses: ./.github/workflows/registry.yml