name: Basic Workflow
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    install_dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install poetry
              run: pipx install poetry
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'poetry'
            - name: Installing Dependencies
              run: poetry install
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install poetry
              run: pipx install poetry
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'poetry'
            - name: Installing Dependencies
              run: poetry install --with test
            - run: poetry run pytest